# -*- coding: utf-8 -*-
"""Eruption Projection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZ0Net3cDyy9qVU6lZ9DlMer0szrAnn8

# Instructions
Update the source data in [this Google sheet](https://docs.google.com/spreadsheets/d/1963XmCwd3p57t_Yqysj9eIdV5jzjcjSkrntipLCDfUo/edit?gid=0#gid=0) to get an updated prediction.

We've been pulling the data from the [USGS graphs](https://www.usgs.gov/volcanoes/kilauea/science/monitoring-data-kilauea) and converting them using [PlotDigitizer](https://plotdigitizer.com/).

# Load Data
"""

import pandas as pd

# Construct the export URL for the Google Sheet
sheet_id = '1963XmCwd3p57t_Yqysj9eIdV5jzjcjSkrntipLCDfUo'
gid = '0'
csv_url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}'

# Load the CSV data into a pandas DataFrame
df = pd.read_csv(csv_url)

# Display the first 5 rows of the DataFrame
display(df.head())

"""# Render Graphs"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import matplotlib.dates as mdates
import numpy as np
from scipy.optimize import curve_fit, fsolve # Import curve_fit and fsolve

# Ensure the 'Date' column is in datetime format for the main DataFrame
df['Date'] = pd.to_datetime(df['Date'])

# Determine the start date for the last 3 months
end_date = df['Date'].max()
start_date = end_date - pd.DateOffset(months=3)

# Filter the DataFrame for the last 3 months of data
df_last_3_months = df[(df['Date'] >= start_date) & (df['Date'] <= end_date)].copy()

# Data for the episodic peaks (excluding the current one)
peak_data_for_trendline = {
    'Date': [
        '2025-08-22 07:42:37',
        '2025-09-02 00:47:22',
        '2025-09-18 17:18:56',
        '2025-09-30 17:22:22',
        '2025-10-17 11:02:47',
        '2025-11-09 00:19:32'
    ],
    'Tilt (microradians)': [
        9.471433662,
        11.79226069,
        9.867617108,
        11.29327902,
        9.511201629,
        8.238434164
    ]
}

df_trendline_peaks = pd.DataFrame(peak_data_for_trendline)
df_trendline_peaks['Date'] = pd.to_datetime(df_trendline_peaks['Date'], format='mixed', dayfirst=False)

# Convert dates to Matplotlib's internal numerical format for plotting consistency
# This step is crucial for aligning the x-axis for both plt.plot and sns.regplot
df_last_3_months['Date_num'] = mdates.date2num(df_last_3_months['Date'])
df_trendline_peaks['Date_num'] = mdates.date2num(df_trendline_peaks['Date'])

# Create the plot
plt.figure(figsize=(15, 7))
# Plot the main data using the numerical date column
plt.plot(df_last_3_months['Date_num'], df_last_3_months['Tilt (microradians)'], marker='o', linestyle='-', label='Last 3 Months Data')

# Add the episodic peaks and their linear trendline to the plot
# Use the numerical date column for both x and regression calculation
sns.regplot(x='Date_num',
            y='Tilt (microradians)',
            data=df_trendline_peaks,
            line_kws={'color': 'red', 'linestyle': '--'},
            scatter_kws={'color': 'green', 's': 100, 'marker': 'X'})

# --- Project the trendline forward ---

# Get the coefficients of the linear trendline
# np.polyfit(x, y, 1) returns coefficients [slope, intercept]
slope, intercept = np.polyfit(df_trendline_peaks['Date_num'], df_trendline_peaks['Tilt (microradians)'], 1)
poly_func_linear = np.poly1d([slope, intercept])

# Define future dates for projection (e.g., next 3 months beyond the last peak)
last_peak_date_num = df_trendline_peaks['Date_num'].max()
future_start_date_lin = mdates.num2date(last_peak_date_num) + pd.DateOffset(days=1)
future_end_date_lin = future_start_date_lin + pd.DateOffset(months=3)

# Generate a series of numerical dates for the future projection
future_dates_lin = pd.date_range(start=future_start_date_lin, end=future_end_date_lin, periods=50) # 50 points for a smooth line
future_dates_num_lin = mdates.date2num(future_dates_lin)

# Predict Tilt values for future dates using the trendline equation (y = mx + c)
projected_tilt_lin = poly_func_linear(future_dates_num_lin)

# --- Exponential Saturation Fit for the Latest Episode and Projection ---

# Define the start date for the latest episode's fit
minimum_date_for_exponential = pd.to_datetime('2025-11-09 07:12:25') # Assuming this is still the relevant start

# Filter the original DataFrame for data points from this minimum onwards
df_current_episode_data = df.loc[df['Date'] >= minimum_date_for_exponential].copy()

# Convert dates to Matplotlib's numerical format
df_current_episode_data['Date_num'] = mdates.date2num(df_current_episode_data['Date'])

# Ensure there are enough points for an exponential fit (at least 3 parameters, so ideally >3 points)
if len(df_current_episode_data) >= 4: # Changed to 4 for 3 parameters
    # Define the exponential saturation function
    # x0 is the fixed minimum date_num from the fitting data
    x0_fit = df_current_episode_data['Date_num'].min()
    def exp_saturation_func(x, A, k, C):
        # We subtract x0_fit to effectively shift the start of the exponential curve to 0 for better k estimation
        # This makes 'x' in exp(-k*x) start from the beginning of the current episode data
        return A * (1 - np.exp(-k * (x - x0_fit))) + C

    # Initial guess for parameters: A, k, C
    y_data = df_current_episode_data['Tilt (microradians)']
    x_data = df_current_episode_data['Date_num']

    A_guess = max(y_data) - min(y_data) if (max(y_data) - min(y_data)) > 0 else 1.0 # Ensure positive amplitude
    k_guess = 0.01 # Small positive growth rate
    C_guess = min(y_data) # Offset at the start

    p0 = [A_guess, k_guess, C_guess]

    try:
        # bounds ensure A and k are positive, as expected for saturation
        params, covariance = curve_fit(exp_saturation_func, x_data, y_data, p0=p0, maxfev=5000,
                                       bounds=([0, 0, -np.inf], [np.inf, np.inf, np.inf]))
        A_exp, k_exp, C_exp = params
        poly_func_exponential = lambda x: exp_saturation_func(x, A_exp, k_exp, C_exp)

        # Define future dates for the exponential projection
        last_point_current_episode_num = df_current_episode_data['Date_num'].max()
        future_exp_start_date = mdates.num2date(last_point_current_episode_num) + pd.DateOffset(days=1)
        future_exp_end_date = future_exp_start_date + pd.DateOffset(months=2) # Project 2 months beyond

        # Generate a series of numerical dates for the full exponential line (fit + projection)
        full_exp_dates_num = np.linspace(df_current_episode_data['Date_num'].min(),
                                          mdates.date2num(future_exp_end_date), 100)
        projected_tilt_full_exp = poly_func_exponential(full_exp_dates_num)

        # --- Find the first intersection point of the exponential projection with the first linear trendline ---
        intersection_date_num = None
        intersection_tilt = None

        # Function to find roots: exp_saturation_func - linear_func = 0
        def diff_func_linear_exp(x):
            return poly_func_exponential(x) - poly_func_linear(x)

        # The earliest date from which both projections are valid
        projection_start_num = max(df_trendline_peaks['Date_num'].max(), df_current_episode_data['Date_num'].max())

        try:
            # Provide an initial guess for fsolve in the future range
            # A point within the projected range, after current data max
            initial_guess_for_fsolve_lin = projection_start_num + (mdates.date2num(future_end_date_lin) - projection_start_num) / 2
            # Ensure the guess is after the last data point of the current episode
            initial_guess_for_fsolve_lin = max(initial_guess_for_fsolve_lin, last_point_current_episode_num + 1)

            root_lin = fsolve(diff_func_linear_exp, initial_guess_for_fsolve_lin)[0]

            if root_lin > projection_start_num and poly_func_linear(root_lin) > -20 and poly_func_linear(root_lin) < 15: # Check if within reasonable plot limits
                intersection_date_num = root_lin
                intersection_tilt = poly_func_linear(intersection_date_num)

        except Exception as e:
            # print(f"Could not find intersection with linear trendline (all peaks): {e}")
            intersection_date_num = None # Reset if error or no valid root found

        # Clip projections at the intersection point if found
        if intersection_date_num is not None:
            # Clip linear projection
            mask_lin = future_dates_num_lin <= intersection_date_num
            future_dates_num_lin_clipped = future_dates_num_lin[mask_lin]
            projected_tilt_lin_clipped = projected_tilt_lin[mask_lin]
            if future_dates_num_lin_clipped.size > 0 and not np.isclose(future_dates_num_lin_clipped[-1], intersection_date_num):
                 future_dates_num_lin_clipped = np.append(future_dates_num_lin_clipped, intersection_date_num)
                 projected_tilt_lin_clipped = np.append(projected_tilt_lin_clipped, intersection_tilt)
            elif future_dates_num_lin_clipped.size == 0: # If intersection is before start of linear projection
                future_dates_num_lin_clipped = np.array([intersection_date_num])
                projected_tilt_lin_clipped = np.array([intersection_tilt])

            # Clip exponential projection
            mask_exp = full_exp_dates_num <= intersection_date_num
            full_exp_dates_num_clipped = full_exp_dates_num[mask_exp]
            projected_tilt_full_exp_clipped = projected_tilt_full_exp[mask_exp]
            if full_exp_dates_num_clipped.size > 0 and not np.isclose(full_exp_dates_num_clipped[-1], intersection_date_num):
                 full_exp_dates_num_clipped = np.append(full_exp_dates_num_clipped, intersection_date_num)
                 projected_tilt_full_exp_clipped = np.append(projected_tilt_full_exp_clipped, intersection_tilt)
            elif full_exp_dates_num_clipped.size == 0: # If intersection is before start of exp projection
                full_exp_dates_num_clipped = np.array([intersection_date_num])
                projected_tilt_full_exp_clipped = np.array([intersection_tilt])

        else: # If no intersection found, plot full projections
            future_dates_num_lin_clipped = future_dates_num_lin
            projected_tilt_lin_clipped = projected_tilt_lin
            full_exp_dates_num_clipped = full_exp_dates_num
            projected_tilt_full_exp_clipped = projected_tilt_full_exp

        # Plot the projected trendlines (clipped or full)
        plt.plot(future_dates_num_lin_clipped, projected_tilt_lin_clipped, color='red', linestyle='--', label='Episodic Peak Trendline (Last 6 months)')
        plt.plot(full_exp_dates_num_clipped, projected_tilt_full_exp_clipped,
                 color='cyan', linestyle='-', linewidth=2, label='Current Episode Exponential Fit & Projection')

        # Plot the data points for the current episode (optional, for visual clarity)
        plt.scatter(df_current_episode_data['Date_num'], df_current_episode_data['Tilt (microradians)'],
                    color='darkviolet', marker='s', s=40, alpha=0.7)

        # Label the intersection point
        if intersection_date_num is not None:
            intersection_dt = mdates.num2date(intersection_date_num)
            label_text = f"Fountain Event: {intersection_dt.strftime('%Y-%m-%d %H:%M')}\nTilt: {intersection_tilt:.2f}"
            plt.scatter(intersection_date_num, intersection_tilt, color='red', marker='*', s=300, edgecolor='black', zorder=5)
            plt.annotate(label_text,
                         (intersection_date_num, intersection_tilt),
                         textcoords="offset points",
                         xytext=(10, 10),
                         ha='left',
                         bbox=dict(boxstyle="round,pad=0.3", fc="yellow", ec="b", lw=1, alpha=0.7))

        # --- New: Trendline for last 3 peaks and its projection ---
        last_3_peaks_data = df_trendline_peaks.tail(3).copy()
        slope_3_peaks, intercept_3_peaks = np.polyfit(last_3_peaks_data['Date_num'], last_3_peaks_data['Tilt (microradians)'], 1)
        poly_func_3_peaks = np.poly1d([slope_3_peaks, intercept_3_peaks])

        future_start_date_3_peaks = mdates.num2date(last_3_peaks_data['Date_num'].max()) + pd.DateOffset(days=1)
        future_end_date_3_peaks = future_start_date_3_peaks + pd.DateOffset(months=3)
        future_dates_3_peaks = pd.date_range(start=future_start_date_3_peaks, end=future_end_date_3_peaks, periods=50)
        future_dates_num_3_peaks = mdates.date2num(future_dates_3_peaks)
        projected_tilt_3_peaks = poly_func_3_peaks(future_dates_num_3_peaks)

        # Find intersection with the current episode exponential projection (Last 3 Peaks vs Exponential)
        intersection_date_num_new = None
        intersection_tilt_new = None

        def diff_func_3_peaks_exp(x):
            return poly_func_exponential(x) - poly_func_3_peaks(x)

        # The new linear projection starts after last_3_peaks_data.max()
        projection_start_num_new = max(last_3_peaks_data['Date_num'].max(), df_current_episode_data['Date_num'].max())

        try:
            # Provide an initial guess for fsolve
            initial_guess_for_fsolve_3_peaks = projection_start_num_new + (mdates.date2num(future_end_date_3_peaks) - projection_start_num_new) / 2
            # Ensure the guess is after the last data point of the current episode
            initial_guess_for_fsolve_3_peaks = max(initial_guess_for_fsolve_3_peaks, last_point_current_episode_num + 1)

            root_new = fsolve(diff_func_3_peaks_exp, initial_guess_for_fsolve_3_peaks)[0]

            if root_new > projection_start_num_new and poly_func_3_peaks(root_new) > -20 and poly_func_3_peaks(root_new) < 15: # Check if within reasonable plot limits
                intersection_date_num_new = root_new
                intersection_tilt_new = poly_func_3_peaks(intersection_date_num_new)

        except Exception as e:
            # print(f"Could not find intersection with last 3 peaks trendline: {e}")
            intersection_date_num_new = None # Reset if error or no valid root found

        # Clip the new linear projection at its intersection point if found
        if intersection_date_num_new is not None:
            mask_3_peaks = future_dates_num_3_peaks <= intersection_date_num_new
            future_dates_num_3_peaks_clipped = future_dates_num_3_peaks[mask_3_peaks]
            projected_tilt_3_peaks_clipped = projected_tilt_3_peaks[mask_3_peaks]
            if future_dates_num_3_peaks_clipped.size > 0 and not np.isclose(future_dates_num_3_peaks_clipped[-1], intersection_date_num_new):
                future_dates_num_3_peaks_clipped = np.append(future_dates_num_3_peaks_clipped, intersection_date_num_new)
                projected_tilt_3_peaks_clipped = np.append(projected_tilt_3_peaks_clipped, intersection_tilt_new)
            elif future_dates_num_3_peaks_clipped.size == 0:
                future_dates_num_3_peaks_clipped = np.array([intersection_date_num_new])
                projected_tilt_3_peaks_clipped = np.array([intersection_tilt_new])
        else:
            future_dates_num_3_peaks_clipped = future_dates_num_3_peaks
            projected_tilt_3_peaks_clipped = projected_tilt_3_peaks

        plt.plot(future_dates_num_3_peaks_clipped, projected_tilt_3_peaks_clipped, color='darkorange', linestyle='-.', label='Episode Peak Trendline (Last 3 episodes)')

        if intersection_date_num_new is not None:
            intersection_dt_new = mdates.num2date(intersection_date_num_new)
            label_text_new = f"Earliest likely fountain event: {intersection_dt_new.strftime('%Y-%m-%d %H:%M')}\nTilt: {intersection_tilt_new:.2f}"
            plt.scatter(intersection_date_num_new, intersection_tilt_new, color='purple', marker='^', s=300, edgecolor='black', zorder=5)
            plt.annotate(label_text_new,
                         (intersection_date_num_new, intersection_tilt_new),
                         textcoords="offset points",
                         xytext=(10, -30),
                         ha='left',
                         bbox=dict(boxstyle="round,pad=0.3", fc="lightgreen", ec="b", lw=1, alpha=0.7))

    except RuntimeError as e:
        print(f"Warning: Could not perform exponential fit: {e}. Plotting linear projection unclipped.")
        plt.plot(future_dates_num_lin, projected_tilt_lin, color='blue', linestyle=':', label='Episodic Peak Trendline (Last 6 months)')

else:
    print("Warning: Not enough data points for an exponential fit for the current episode (need at least 4 for 3 parameters). Skipping exponential fit and projection.")
    # If no exponential fit, plot linear projection unclipped
    plt.plot(future_dates_num_lin, projected_tilt_lin, color='blue', linestyle=':', label='Episodic Peak Trendline (Last 6 months)')

# Set x-axis ticks and labels to represent dates properly
ax = plt.gca()

# Set major ticks for weeks and minor ticks for days
ax.xaxis.set_major_locator(mdates.WeekdayLocator()) # Major ticks for each week
ax.xaxis.set_minor_locator(mdates.DayLocator())    # Minor ticks for each day

# Use AutoDateFormatter for cleaner date handling, based on the major locator
formatter = mdates.AutoDateFormatter(ax.xaxis.get_major_locator())
ax.xaxis.set_major_formatter(formatter)

# Set x-axis limits
ax.set_xlim(mdates.date2num(pd.to_datetime('2025-10-15')), mdates.date2num(pd.to_datetime('2025-12-01')))
# ax.set_xlim(df_last_3_months['Date_num'].min(), mdates.date2num(pd.to_datetime('2025-12-01')))

# Set y-axis limits
ax.set_ylim(-20, 15)

plt.title('Electronic Tilt at Kīlauea Summit Over Last 3 Months with Trendlines and Projections')
plt.xlabel('Date (Pacific/Honolulu Time)')
plt.ylabel('Electronic Tilt - Azimuth 300 (microradians)')
plt.grid(True, which='major', linestyle='-', linewidth=0.7) # Major gridlines
plt.grid(True, which='minor', linestyle=':', linewidth=0.5) # Minor gridlines
plt.xticks(rotation=45)
plt.tight_layout()
plt.legend()
plt.show()